masters:
  hosts:
    master001:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    master002:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    master003:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root

workers:
  hosts:
    worker001:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    worker002:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    worker003:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    worker004:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
    worker005:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root

storages:
  hosts:
    storage-nfs:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root

loadbalancers:
  hosts:
    loadbalancer001:
      ansible_host: REPLACE_WITH_IP
      ansible_user: root
