kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
