---
- hosts: all
  become: yes
  become_user: root
  vars_files:
  - variables.yaml
  tasks:
  - name: Confirm if you want to create Ingress controller
    tags: install-dashboard
    pause:
      prompt: "Do you want to create Ingress controller? (yes/no)"
    register: create_ingress_controller
  - name: Writing Ingress manifest
    tags: install-ingress
    copy:
      src: ../manifests/ingress/nginx-ingress.yaml
      dest: /home/ubuntu/nginx-ingress.yaml
    when: create_ingress_controller.user_input | bool
  - name: Apply Ingress manifest
    tags: install-ingress
    shell: |
      kubectl apply -f /home/ubuntu/nginx-ingress.yaml
      rm -rf /home/ubuntu/nginx-ingress.yaml
    when: create_ingress_controller.user_input | bool


  - name: Confirm if you want to create Kubernetes dashboard
    tags: install-dashboard
    pause:
      prompt: "Do you want to create kubernetes dashboard? (yes/no)"
    register: create_kubernetes_dashboard
  - name: Writing Kubernetes dashboard manifest
    tags: install-dashboard
    copy:
      src: ../manifests/dashboard/dashboard.yaml
      dest: /home/ubuntu/kubernetes-dashboard.yaml
    when: create_kubernetes_dashboard.user_input | bool
  - name: Apply Kubernetes dashboard manifest
    tags: install-dashboard
    shell: |
      kubectl apply -f /home/ubuntu/kubernetes-dashboard.yaml
      rm -rf /home/ubuntu/kubernetes-dashboard.yaml
    when: create_kubernetes_dashboard.user_input | bool
