K8S_API_ENDPOINTS: REPLACE_WITH_IP
K8S_API_PORT: 6443
CLUSTER_NAME: TABANAN
PROXY:
  http_proxy: http://10.10.0.10:8118
  https_proxy: http://10.10.0.10:8118
  no_proxy: localhost,127.0.0.1,10.96.0.1,10.96.0.10
